return {
    Ambient = Color3.fromRGB(27, 27, 27);
    Brightness = 0.5;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(25, 25, 25);
    ShadowSoftness = 0.2;
    GeographicLatitude = 41.733;
    TimeOfDay = "3:00:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(11, 11, 11);
    FogEnd = 100;
    FogStart = 50;
}