return {
    Ambient = Color3.fromRGB(12, 145, 185);
    Brightness = 3.1;
    ColorShift_Bottom = Color3.fromRGB(154, 168, 165);
    ColorShift_Top = Color3.fromRGB(164, 186, 174);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(118, 226, 85);
    ShadowSoftness = 0.35;
    GeographicLatitude = 41.733;
    TimeOfDay = "13:50:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(0, 234, 255);
    FogEnd = 10000;
    FogStart = 0;
}