return {
	Ambient = Color3.fromRGB(83, 124, 141);
    Brightness = 1.1;
    ColorShift_Bottom = Color3.fromRGB(71, 125, 119);
	ColorShift_Top = Color3.fromRGB(149, 172, 162);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
	OutdoorAmbient = Color3.fromRGB(86, 116, 120);
    ShadowSoftness = 0.17;
    GeographicLatitude = 41.733;
    TimeOfDay = "6:00:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(199, 249, 255);
    FogEnd = 400;
    FogStart = 60;
}