return {
	Ambient = Color3.fromRGB(170, 172, 77);
    Brightness = 0.3;
    ColorShift_Bottom = Color3.fromRGB(74, 93, 62);
    ColorShift_Top = Color3.fromRGB(67, 42, 80);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(102, 103, 46);
    ShadowSoftness = 0.3;
    GeographicLatitude = 41.733;
    TimeOfDay = "7:40:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(192, 187, 151);
    FogEnd = 50000;
    FogStart = 0;
}