return {
	Ambient = Color3.fromRGB(151, 127, 171);
    Brightness = 0.8;
	ColorShift_Bottom = Color3.fromRGB(196, 151, 216);
	ColorShift_Top = Color3.fromRGB(191, 119, 220);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
	OutdoorAmbient = Color3.fromRGB(206, 149, 231);
    ShadowSoftness = 0.2;
    GeographicLatitude = 41.733;
    TimeOfDay = "24:00:00";
    ExposureCompensation = 0;
	FogColor = Color3.fromRGB(45, 49, 49);
	FogEnd = 330;
	FogStart = 60;
}