return {
    Ambient = Color3.fromRGB(197, 180, 114);
    Brightness = 0.8;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(190, 154, 63);
    ShadowSoftness = 0.2;
    GeographicLatitude = 41.733;
    TimeOfDay = "13:50:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(192, 156, 26);
    FogEnd = 200;
    FogStart = 75;
}