return {
	Ambient = Color3.fromRGB(191, 174, 166);
    Brightness = 1;
	ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
	ColorShift_Top = Color3.fromRGB(231, 250, 255);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
	OutdoorAmbient = Color3.fromRGB(189, 164, 150);
    ShadowSoftness = 0.2;
    GeographicLatitude = 41.733;
	TimeOfDay = "9:30:00";
    ExposureCompensation = 0.2;
    FogColor = Color3.fromRGB(0, 0, 0);
    FogEnd = 9000;
    FogStart = 0;
}