return {
    Ambient = Color3.fromRGB(98, 172, 154);
    Brightness = 2.4;
    ColorShift_Bottom = Color3.fromRGB(60, 152, 149);
    ColorShift_Top = Color3.fromRGB(78, 200, 192);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(81, 185, 122);
    ShadowSoftness = 0.25;
    GeographicLatitude = 41.733;
    TimeOfDay = "13:50:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(117, 188, 192);
    FogEnd = 50000;
    FogStart = 0;
}