return {
    Ambient = Color3.fromRGB(94, 54, 54);
    Brightness = 0.5;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(85, 65, 65);
    ShadowSoftness = 0.2;
    GeographicLatitude = 41.733;
    TimeOfDay = "4:30:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(21, 21, 21);
    FogEnd = 130;
    FogStart = 50;
}