return {
	Ambient = Color3.fromRGB(226, 181, 0);
    Brightness = 1;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0.35;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(127, 128, 94);
    ShadowSoftness = 0.2;
    GeographicLatitude = 300;
    TimeOfDay = "12:00:00";
    ExposureCompensation = 0;
	FogColor = Color3.fromRGB(-150000,-150000,-150000);
    FogEnd = 500000000000000;
    FogStart = 50000000000000;
}