return {
    Ambient = Color3.fromRGB(129, 166, 29);
    Brightness = 0;
    ColorShift_Bottom = Color3.fromRGB(61, 131, 55);
    ColorShift_Top = Color3.fromRGB(132, 186, 178);
    EnvironmentDiffuseScale = 1;
    EnvironmentSpecularScale = 0;
    GlobalShadows = false;
    OutdoorAmbient = Color3.fromRGB(72, 172, 72);
    ShadowSoftness = 0.25;
    GeographicLatitude = 41.733;
    TimeOfDay = "13:30:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(117, 188, 192);
    FogEnd = 50000;
    FogStart = 0;
}