return {
	Ambient = Color3.fromRGB(58, 70, 69);
	Brightness = 2.75;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0.8;
    EnvironmentSpecularScale = 1;
    GlobalShadows = true;
	OutdoorAmbient = Color3.fromRGB(149, 152, 93);
    ShadowSoftness = 0.35;
    GeographicLatitude = 41.733;
    TimeOfDay = "15:00:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(160, 192, 189);
    FogEnd = 3000;
    FogStart = 1500;
    
    --other
    --   GlobalWind = Vector3.new(150, 0, 40)
}
--[[] old lighytiong
return {
	Ambient = Color3.fromRGB(0, 0, 0);
	Brightness = 1.15;
	ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
	ColorShift_Top = Color3.fromRGB(0, 0, 0);
	EnvironmentDiffuseScale = 0.35;
	EnvironmentSpecularScale = 1;
	GlobalShadows = true;
	OutdoorAmbient = Color3.fromRGB(149, 152, 93);
	ShadowSoftness = 0.35;
	GeographicLatitude = 41.733;
	TimeOfDay = "15:00:00";
	ExposureCompensation = 0;
	FogColor = Color3.fromRGB(160, 192, 189);
	FogEnd = 3000;
	FogStart = 1500;

	--other
	--   GlobalWind = Vector3.new(150, 0, 40)
}
--[]]