[package]
name = "encodedvenom/fastcastredux"
description = "A port of FastCastRedux into Wally"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1.0.1"