return {
	Ambient = Color3.fromRGB(131, 131, 188);
    Brightness = 0.25;
	ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
	ColorShift_Top = Color3.fromRGB(74, 74, 107);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(102, 103, 46);
    ShadowSoftness = 0.3;
    GeographicLatitude = 41.733;
	TimeOfDay = "-17:26:50";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(192, 187, 151);
    FogEnd = 500000;
    FogStart = 0;
}