return {
	Ambient = Color3.fromRGB(110, 110, 120);
    Brightness = 1;
    ColorShift_Bottom = Color3.fromRGB(83, 99, 95);
	ColorShift_Top = Color3.fromRGB(83, 99, 95);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
	OutdoorAmbient = Color3.fromRGB(110, 110, 120);
    ShadowSoftness = 0.25;
    GeographicLatitude = 41.733;
    TimeOfDay = "3:50:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(19, 25, 21);
    FogEnd = 50000;
    FogStart = 0;
}