return {
    Ambient = Color3.fromRGB(139, 120, 118);
    Brightness = 1.2;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(103, 128, 101);
    ShadowSoftness = 0.2;
    GeographicLatitude = 41.733;
    TimeOfDay = "13:00:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(192, 192, 192);
    FogEnd = 50000;
    FogStart = 0;
}