return {
	Ambient = Color3.fromRGB(138, 138, 138);
    Brightness = 1.575;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = false;
    OutdoorAmbient = Color3.fromRGB(128, 88, 88);
    ShadowSoftness = 0.2;
    GeographicLatitude = 41.733;
    TimeOfDay = "6:00:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(192, 192, 192);
    FogEnd = 50000;
    FogStart = 0;
}