return {
    Ambient = Color3.fromRGB(102, 137, 139);
    Brightness = 1;
    ColorShift_Bottom = Color3.fromRGB(0, 0, 0);
    ColorShift_Top = Color3.fromRGB(0, 0, 0);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(93, 128, 128);
    ShadowSoftness = 0;
    GeographicLatitude = 62;
    TimeOfDay = "14:24:00";
    ExposureCompensation = 0.2;
    FogColor = Color3.fromRGB(0, 0, 0);
    FogEnd = 2001;
    FogStart = 100;
}