return {
    Ambient = Color3.fromRGB(114, 166, 162);
    Brightness = 2.75;
    ColorShift_Bottom = Color3.fromRGB(63, 131, 131);
    ColorShift_Top = Color3.fromRGB(164, 186, 174);
    EnvironmentDiffuseScale = 0;
    EnvironmentSpecularScale = 0;
    GlobalShadows = true;
    OutdoorAmbient = Color3.fromRGB(97, 172, 132);
    ShadowSoftness = 0.25;
    GeographicLatitude = 41.733;
    TimeOfDay = "13:30:00";
    ExposureCompensation = 0;
    FogColor = Color3.fromRGB(117, 188, 192);
    FogEnd = 50000;
    FogStart = 0;
}